services:
  facet:
    build:
      context: .
      args:
        USERNAME: ${USERNAME}
        UID: ${UID}
        GID: ${GID}
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
    working_dir: "/facet"
    volumes:
      - "../:/facet"
