From Facet.TypeSystem Require Export TypeSafetyHiddenFrameBaseCore.
From Facet.TypeSystem Require Export TypeSafetyHiddenFrameBaseCapture.
From Facet.TypeSystem Require Export TypeSafetyHiddenFrameBaseCopyStore.
From Facet.TypeSystem Require Export TypeSafetyHiddenFrameBaseEmpty.
From Facet.TypeSystem Require Export TypeSafetyHiddenFrameBaseStoreRefs.
